[package]
name = "embedded-graphics-framebuf"
version = "0.5.0"
edition = "2021"
authors = [
  "Bernard Kobos <bkobos@gmail.com>",
  "Jounathaen <jounathaen at mail dot de>",
]
license = "MIT"
description = "Frame buffer helper for embedded-graphics"

[dependencies]
embedded-graphics = "0.8"
embedded-dma = {version = "0.2.0", optional = true}

[features]
default = ["embedded-dma"]
embedded-dma = ["dep:embedded-dma"]
