name: Continuous integration
on:
  pull_request:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Stable
        uses: dtolnay/rust-toolchain@stable
      - name: Release build std
        run: cargo build --release --all-features

  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v5

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Run cargo test
        run: cargo test

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Nightly with clippy
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: clippy
      - name: Clippy std
        run: cargo clippy --all-features -- -D warnings
      - name: Clippy no_std
        run: cargo clippy --no-default-features -- -D warnings

  doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Stable
        uses: dtolnay/rust-toolchain@stable
      - name: Documentation build
        run: cargo doc

  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install cargo-tarpaulin
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-tarpaulin

      - name: Run cargo-tarpaulin
        run: cargo tarpaulin --out Xml -- --test-threads 1

      #- name: Upload to codecov.io
        #uses: codecov/codecov-action@v1.0.2
        #with:
          #token: ${{secrets.CODECOV_TOKEN}}

      #- name: Archive code coverage results
        #uses: actions/upload-artifact@v1
        #with:
          #name: code-coverage-report
          #path: cobertura.xml

  security-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Security audit
        uses: rustsec/audit-check@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
